version: "3.8"

services:
  api:
    image: thumbnailapi
    container_name: thumbnailapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5035:5035"

  localstack:
    container_name: localstack_thumbnail
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - DEBUG=1
      - SERVICES=s3,lambda
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - DATA_DIR=/tmp/localstack/data
      - EAGER_SERVICE_LOADING=1
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init_s3.sh:/docker-entrypoint-initaws.d/init_s3.sh"
      - "./test_lambda/ThumbnailLambda.zip:/docker-entrypoint-initaws.d/ThumbnailLambda.zip"
      - "./test_lambda/iam_policy.json:/docker-entrypoint-initaws.d/iam_policy.json"
      - "./test_lambda/s3notification.json:/docker-entrypoint-initaws.d/s3notification.json"
    

  